/* global window */
/* =========================================================================
   Wealthoria, bilingual content (English + Kannada).
   All visible copy lives here so the EN / ಕನ್ನಡ toggle can swap the whole
   shell + demo content. Kannada strings are demo translations, have a
   native reviewer confirm before publishing.
   ========================================================================= */

const CONTENT = {
  en: {
    dir: "ltr",
    nav: {
      links: [
        { id: "why", label: "Why us" },
        { id: "programs", label: "Programs" },
        { id: "process", label: "How it works" },
        { id: "seminars", label: "Seminars" },
        { id: "resources", label: "Resources" },
        { id: "about", label: "About" },
      ],
      cta: "Book consultation",
    },
    hero: {
      eyebrow: "Financial education · Karnataka",
      title: ["Learning is the", "first investment"],
      lede: "Understand money, markets and investing before you ever put a rupee at risk. Structured financial education in plain language, and in Kannada.",
      ctaPrimary: "Start learning",
      ctaSecondary: "Book free consultation",
      trust: "Trusted by 800+ learners across Karnataka",
      card: {
        title: "Your learning path",
        level: "Beginner",
        progress: "2 of 6 modules complete",
        modules: [
          { t: "What is money, really?", s: "done" },
          { t: "Needs, wants & saving", s: "done" },
          { t: "Stock market fundamentals", s: "now" },
          { t: "Mutual funds & SIPs", s: "lock" },
        ],
        cta: "Continue learning",
      },
    },
    ticker: ["Learn in Kannada & English", "No tips, no signals", "800+ active clients", "Risk before returns", "Long-term wealth, not luck", "All over Karnataka", "Education first"],
    narrative: {
      eyebrow: "001 \u00b7 The problem",
      l1: "Tips groups gamble your savings.",
      l2: "Courses sell hype.",
      l3: "Nobody teaches the basics.",
      resolve: "We start with education.",
      sub: "No signals, no predictions, no shortcuts. Just a calm, structured path from your first rupee to independent, informed investing.",
    },
    metrics: [
      { n: "80+", l: "Students educated", c: "Classroom-first, not webinar spam" },
      { n: "800+", l: "Active clients", c: "Families investing with a plan" },
      { n: "Karnataka", l: "Reach", c: "Tier 2 and 3 cities included" },
      { n: "1,200+", l: "Learning hours delivered", c: "In Kannada and English" },
    ],
    why: {
      eyebrow: "Why Wealthoria",
      title: "Education first. Always.",
      sub: "We believe wealth is built on understanding, not luck. Here is what we put before everything else.",
      items: [
        { ic: "book", t: "Knowledge before capital", d: "Learn how money and markets actually work before you invest a single rupee." },
        { ic: "trending", t: "Investing before trading", d: "We teach patient, long-term investing, never speculation or quick-flip trading." },
        { ic: "languages", t: "Regional language learning", d: "Concepts taught in Kannada and English, so language is never a barrier to literacy." },
        { ic: "compass", t: "Independent decision making", d: "We don't give tips. We give you the framework to decide for yourself, with confidence." },
        { ic: "shield", t: "Risk awareness", d: "Understand risk before reward. Every lesson grounds you in what can go wrong, and why." },
        { ic: "sprout", t: "Long-term wealth creation", d: "Habits and discipline that compound over decades, not headlines that fade in days." },
      ],
    },
    programs: {
      eyebrow: "Learning programs",
      title: "A structured path, step by step",
      sub: "Six focused programs that take you from the basics of money to confident, independent investing.",
      tabs: [
        { id: "all", label: "All" },
        { id: "foundations", label: "Foundations" },
        { id: "markets", label: "Markets" },
        { id: "mindset", label: "Mindset" },
      ],
      cta: "View program",
      items: [
        { ic: "pie", cat: "markets", t: "Stock market fundamentals", d: "How shares, indices and the market really work, explained from zero.", level: "Beginner", modules: "8 modules" },
        { ic: "layers", cat: "markets", t: "Mutual funds & SIPs", d: "Build wealth steadily through diversified funds and disciplined SIPs.", level: "Beginner", modules: "6 modules" },
        { ic: "wallet", cat: "foundations", t: "Personal finance", d: "Budgeting, saving, debt and emergency funds, your financial foundation.", level: "Beginner", modules: "7 modules" },
        { ic: "target", cat: "foundations", t: "Financial planning", d: "Set goals, plan for life events, and map money to the life you want.", level: "Intermediate", modules: "5 modules" },
        { ic: "brain", cat: "mindset", t: "Investor psychology", d: "Master the emotions (fear, greed, patience) that decide real returns.", level: "Intermediate", modules: "4 modules" },
        { ic: "scale", cat: "mindset", t: "Asset allocation", d: "Balance risk across equity, debt and gold to match your goals.", level: "Advanced", modules: "5 modules" },
      ],
    },
    process: {
      eyebrow: "How it works",
      title: "From confused to confident in four steps",
      sub: "A calm, repeatable process, the same one we use with every learner.",
      steps: [
        { t: "Learn", d: "Start with the fundamentals of money, markets and investing in plain language." },
        { t: "Understand risk", d: "Before any reward, learn exactly what can go wrong and how to manage it." },
        { t: "Build knowledge", d: "Layer concepts gradually until the full picture clicks into place." },
        { t: "Invest with discipline", d: "Apply what you know patiently, for the long term, on your own terms." },
      ],
    },
    founder: {
      eyebrow: "Meet the founders",
      title: "Two people, one mission",
      sub: "We started Wealthoria to build a financially aware Karnataka, one learner who can think for themselves at a time.",
      people: [
        {
          photoLabel: "Sandeep's photo, drop image",
          name: "Sandeep M. Kalburgi",
          photo: "assets/founder-sandeep.jpg",
          role: "Director, Business & Management",
          quote: "Every share represents a piece of human productivity. Invest in that, not in price movements.",
          creds: [
            "5+ years personal investment journey",
            "Business strategy & operations",
            "Company governance & management",
            "Curriculum design & programme delivery",
            "NISM certifications (NISM I, VA, VII, VIII)",
            "NSE, BSE, MCX broking license holder",
          ],
        },
        {
          photoLabel: "Manjunath's photo, drop image",
          name: "Manjunath K.S.",
          photo: "assets/founder-manjunath.jpg",
          role: "Director, Research & Content",
          quote: "The goal of investing is not to beat everyone else. It is to secure your financial independence.",
          creds: [
            "NISM Certified Research Analyst (Series XV and V)",
            "Content creator, Stock Market Kannada (1L+ subscribers)",
            "6+ years financial content creation",
            "Live market analysis & investment research",
            "10+ years personal investment journey",
          ],
        },
      ],
    },
    testimonials: {
      eyebrow: "What learners say",
      title: "Real people, real understanding",
      items: [
        { q: "I finally understand SIPs and risk instead of just following tips. I invest on my own now, calmly.", n: "Priya R.", r: "Software engineer · Bengaluru" },
        { q: "The Kannada sessions made everything click for my parents. Financial literacy in our own language is powerful.", n: "Manjunath S.", r: "Business owner · Hubballi" },
        { q: "No hype, no get-rich-quick. Just clear education that changed how I think about money.", n: "Anita K.", r: "College student · Mysuru" },
        { q: "I learned to understand risk before reward. That single shift saved me from a bad decision.", n: "Rahul D.", r: "Salaried professional · Mangaluru" },
        { q: "Structured, patient and honest. Exactly how financial education should be taught.", n: "Sahana B.", r: "Teacher · Belagavi" },
      ],
    },
    youtube: {
      eyebrow: "Watch & learn",
      title: "Free lessons on our channel",
      sub: "Bite-sized financial education, published every week, in Kannada and English.",
      cta: "Visit our channel",
      items: [
        { t: "What is a mutual fund? Explained simply", dur: "12:40", views: "24K views", tag: "Mutual funds", feat: true },
        { t: "5 money mistakes first-time investors make", dur: "08:15", views: "18K views", tag: "Personal finance" },
        { t: "SIP vs lumpsum: which is right for you?", dur: "10:02", views: "31K views", tag: "Investing" },
      ],
    },
    seminars: {
      eyebrow: "Upcoming seminars & events",
      title: "Learn with us, in person and online",
      sub: "Free and paid sessions across Karnataka. Reserve your seat early, they fill up.",
      cta: "Register",
      seatsLabel: "seats left",
      items: [
        { d: "14", m: "Jun", t: "Stock market fundamentals, live workshop", city: "Bengaluru", mode: "In person", seats: "18" },
        { d: "21", m: "Jun", t: "Mutual funds & SIPs masterclass (Kannada)", city: "Online", mode: "Online", seats: "120" },
        { d: "05", m: "Jul", t: "Personal finance for young professionals", city: "Hubballi", mode: "In person", seats: "32" },
      ],
    },
    library: {
      eyebrow: "Free knowledge library",
      title: "Guides, calculators & cheat-sheets",
      sub: "Self-serve resources to keep learning between sessions, all free.",
      items: [
        { ic: "file", tag: "Guide", t: "Beginner's guide to investing", d: "A plain-language primer covering the absolute basics." },
        { ic: "calc", tag: "Calculator", t: "SIP & goal calculator", d: "See how disciplined monthly investing compounds over time." },
        { ic: "list", tag: "Checklist", t: "Personal finance checklist", d: "The 10 money habits to set up before you invest." },
        { ic: "book", tag: "Glossary", t: "Investing terms, demystified", d: "Every key term explained in one simple place." },
      ],
    },
    consult: {
      eyebrow: "Book a free consultation",
      title: "Not sure where to start?",
      sub: "Tell us a little about yourself and we'll recommend the right learning path, completely free, no obligation.",
      points: [
        { ic: "compass", t: "A path matched to you", d: "We map your goals and experience to the right programs." },
        { ic: "languages", t: "In your language", d: "Talk to us in Kannada or English, whatever's comfortable." },
        { ic: "shield", t: "Education, not sales", d: "No products pushed. Just honest guidance on learning." },
      ],
      contacts: [
        { ic: "mail", v: "wealthoria.edu@gmail.com", href: "mailto:wealthoria.edu@gmail.com" },
        { ic: "phone", v: "+91 90197 59001", href: "tel:+919019759001" },
        { ic: "pin", v: "Mysuru, Karnataka, India", href: "#" },
      ],
      form: {
        name: "Full name", email: "Email", phone: "Phone", city: "City",
        interest: "I'm interested in", message: "Anything you'd like us to know? (optional)",
        interestOpts: ["Stock market fundamentals", "Mutual funds & SIPs", "Personal finance", "Financial planning", "Not sure yet, guide me"],
        submit: "Request free consultation",
        placeholderName: "e.g. Anand Kumar", placeholderEmail: "you@email.com",
        placeholderPhone: "+91 ", placeholderCity: "e.g. Bengaluru",
        placeholderMsg: "Your goals, questions, or preferred language…",
        errName: "Please enter your name", errEmail: "Enter a valid email", errPhone: "Enter a valid phone number",
        successTitle: "Request received", successMsg: "Thanks! Our team will reach out within one working day to plan your free consultation.",
      },
    },
    faq: {
      eyebrow: "FAQ",
      title: "Questions, answered",
      items: [
        { q: "Do I need any prior knowledge to start?", a: "Not at all. Our programs begin from the absolute basics of money and build up gradually, so first-time learners feel comfortable from day one." },
        { q: "Are the sessions available in Kannada?", a: "Yes. Core programs and many seminars are taught in both Kannada and English, because language should never be a barrier to financial literacy." },
        { q: "Is Wealthoria giving stock tips or advisory?", a: "No. We are a financial education company. We teach you how to think and decide for yourself, we never give tips or recommend specific stocks." },
        { q: "Who are the programs designed for?", a: "First-time investors, young professionals, salaried individuals, business owners and students, anyone who wants to understand money before investing." },
        { q: "Are there free resources to start with?", a: "Yes. Our YouTube channel, knowledge library and select seminars are completely free. You can begin learning today at no cost." },
        { q: "How do I book a consultation?", a: "Use the consultation form above. Tell us your goals and we'll recommend the right learning path, free, with no obligation." },
      ],
    },
    footer: {
      blurb: "Wealthoria is a financial education company on a mission to build a financially aware India, learning before investing, investing before trading.",
      newsletter: "Get a free lesson in your inbox each week",
      newsletterCta: "Join",
      cols: [
        { h: "Learn", links: ["Programs", "Seminars", "Knowledge library", "YouTube channel"] },
        { h: "Company", links: ["About us", "Founder vision", "Careers", "Contact"] },
        { h: "Resources", links: ["Beginner's guide", "Calculators", "Glossary", "Blog"] },
        { h: "Legal", links: ["Privacy policy", "Terms of use", "Disclaimer", "Refund policy"] },
      ],
      disclaimer: "Wealthoria provides financial education only and does not offer investment advisory or guaranteed returns. Investments are subject to market risks.",
      copyright: "© 2026 Wealthoria Education Private Limited",
    },
  },

  kn: {
    dir: "ltr",
    nav: {
      links: [
        { id: "why", label: "ನಾವು" },
        { id: "programs", label: "ಕಾರ್ಯಕ್ರಮಗಳು" },
        { id: "process", label: "ಕೆಲಸ ಹೇಗೆ" },
        { id: "seminars", label: "ಸೆಮಿನಾರ್" },
        { id: "resources", label: "ಸಂಪನ್ಮೂಲಗಳು" },
        { id: "about", label: "ನಮ್ಮ ಬಗ್ಗೆ" },
      ],
      cta: "ಸಮಾಲೋಚನೆ ಕಾಯ್ದಿರಿಸಿ",
    },
    hero: {
      eyebrow: "ಹಣಕಾಸು ಶಿಕ್ಷಣ · ಕರ್ನಾಟಕ",
      title: ["ಹೂಡಿಕೆಗೂ ಮುನ್ನ", "ಕಲಿಕೆ."],
      lede: "ಒಂದು ರೂಪಾಯಿ ಅಪಾಯಕ್ಕೆ ಒಡ್ಡುವ ಮೊದಲು, ಮಾರುಕಟ್ಟೆ ಮತ್ತು ಹೂಡಿಕೆಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ. ಸರಳ ಭಾಷೆಯಲ್ಲಿ, ಮತ್ತು ಕನ್ನಡದಲ್ಲಿ, ರಚನಾತ್ಮಕ ಹಣಕಾಸು ಶಿಕ್ಷಣ.",
      ctaPrimary: "ಕಲಿಕೆ ಆರಂಭಿಸಿ",
      ctaSecondary: "ಉಚಿತವಾಗಿ ಸ್ಥಳ ಕಾಯ್ದಿರಿಸಿ",
      trust: "ಕರ್ನಾಟಕದಾದ್ಯಂತ 800+ ಕಲಿಯುವವರ ವಿಶ್ವಾಸ",
      card: {
        title: "ನಿಮ್ಮ ಕಲಿಕಾ ಮಾರ್ಗ",
        level: "ಆರಂಭಿಕ",
        progress: "6 ರಲ್ಲಿ 2 ಮಾಡ್ಯೂಲ್ ಪೂರ್ಣ",
        modules: [
          { t: "ಹಣ ಎಂದರೇನು?", s: "done" },
          { t: "ಅಗತ್ಯ, ಬಯಕೆ ಮತ್ತು ಉಳಿತಾಯ", s: "done" },
          { t: "ಷೇರು ಮಾರುಕಟ್ಟೆ ಮೂಲಾಂಶಗಳು", s: "now" },
          { t: "ಮ್ಯೂಚುವಲ್ ಫಂಡ್ ಮತ್ತು SIP", s: "lock" },
        ],
        cta: "ಕಲಿಕೆ ಮುಂದುವರಿಸಿ",
      },
    },
    ticker: ["ಕನ್ನಡ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಕಲಿಯಿರಿ", "ಸಲಹೆಗಳಿಲ್ಲ, ಸಿಗ್ನಲ್‌ಗಳಿಲ್ಲ", "800+ ಸಕ್ರಿಯ ಗ್ರಾಹಕರು", "ಲಾಭಕ್ಕೂ ಮುನ್ನ ಅಪಾಯದ ಅರಿವು", "ಅದೃಷ್ಟವಲ್ಲ, ದೀರ್ಘಾವಧಿ ಸಂಪತ್ತು", "ಕರ್ನಾಟಕದಾದ್ಯಂತ", "ಮೊದಲು ಶಿಕ್ಷಣ"],
    narrative: {
      eyebrow: "001 \u00b7 ಸಮಸ್ಯೆ",
      l1: "ಟಿಪ್ಸ್ ಗುಂಪುಗಳು ನಿಮ್ಮ ಉಳಿತಾಯವನ್ನು ಜೂಜಾಡುತ್ತವೆ.",
      l2: "ಕೋರ್ಸ್‌ಗಳು ಹೈಪ್ ಮಾರುತ್ತವೆ.",
      l3: "ಮೂಲಭೂತ ವಿಷಯ ಯಾರೂ ಕಲಿಸುವುದಿಲ್ಲ.",
      resolve: "ನಾವು ಶಿಕ್ಷಣದಿಂದ ಆರಂಭಿಸುತ್ತೇವೆ.",
      sub: "ಸಿಗ್ನಲ್ ಇಲ್ಲ, ಭವಿಷ್ಯವಾಣಿ ಇಲ್ಲ, ಶಾರ್ಟ್‌ಕಟ್ ಇಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ರೂಪಾಯಿಯಿಂದ ಸ್ವತಂತ್ರ ಹೂಡಿಕೆಯವರೆಗೆ ಶಾಂತ, ರಚನಾತ್ಮಕ ದಾರಿ.",
    },
    metrics: [
      { n: "80+", l: "ಶಿಕ್ಷಣ ಪಡೆದ ವಿದ್ಯಾರ್ಥಿಗಳು", c: "ತರಗತಿ-ಮೊದಲ ಕಲಿಕೆ" },
      { n: "800+", l: "ಸಕ್ರಿಯ ಗ್ರಾಹಕರು", c: "ಯೋಜನೆಯೊಂದಿಗೆ ಹೂಡುವ ಕುಟುಂಬಗಳು" },
      { n: "ಕರ್ನಾಟಕದಾದ್ಯಂತ", l: "ವ್ಯಾಪ್ತಿ", c: "ಟಯರ್ 2 ಮತ್ತು 3 ನಗರಗಳೂ ಸೇರಿ" },
      { n: "1,200+", l: "ಒದಗಿಸಿದ ಕಲಿಕಾ ಗಂಟೆಗಳು", c: "ಕನ್ನಡ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ" },
    ],
    why: {
      eyebrow: "ಏಕೆ Wealthoria",
      title: "ಮೊದಲು ಶಿಕ್ಷಣ. ಯಾವಾಗಲೂ.",
      sub: "ಸಂಪತ್ತು ಅದೃಷ್ಟದಿಂದಲ್ಲ, ತಿಳಿವಳಿಕೆಯಿಂದ ಬೆಳೆಯುತ್ತದೆ ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ. ನಾವು ಎಲ್ಲಕ್ಕಿಂತ ಮೊದಲು ಇಡುವುದು ಇದನ್ನು.",
      items: [
        { ic: "book", t: "ಬಂಡವಾಳಕ್ಕಿಂತ ಮೊದಲು ಜ್ಞಾನ", d: "ಒಂದು ರೂಪಾಯಿ ಹೂಡುವ ಮೊದಲು ಹಣ ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದು ಕಲಿಯಿರಿ." },
        { ic: "trending", t: "ವ್ಯಾಪಾರಕ್ಕಿಂತ ಮೊದಲು ಹೂಡಿಕೆ", d: "ನಾವು ತಾಳ್ಮೆಯ, ದೀರ್ಘಕಾಲೀನ ಹೂಡಿಕೆಯನ್ನು ಕಲಿಸುತ್ತೇವೆ, ಊಹಾಪೋಹ ಅಲ್ಲ." },
        { ic: "languages", t: "ಪ್ರಾದೇಶಿಕ ಭಾಷೆಯಲ್ಲಿ ಕಲಿಕೆ", d: "ಕನ್ನಡ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಪರಿಕಲ್ಪನೆಗಳು, ಭಾಷೆ ಅಡ್ಡಿಯಾಗದು." },
        { ic: "compass", t: "ಸ್ವತಂತ್ರ ನಿರ್ಧಾರ", d: "ನಾವು ಸಲಹೆ ನೀಡುವುದಿಲ್ಲ. ನೀವೇ ವಿಶ್ವಾಸದಿಂದ ನಿರ್ಧರಿಸಲು ಚೌಕಟ್ಟು ನೀಡುತ್ತೇವೆ." },
        { ic: "shield", t: "ಅಪಾಯದ ಅರಿವು", d: "ಲಾಭಕ್ಕಿಂತ ಮೊದಲು ಅಪಾಯ. ಪ್ರತಿ ಪಾಠವೂ ಏನು ತಪ್ಪಾಗಬಹುದು ಎಂಬುದನ್ನು ತಿಳಿಸುತ್ತದೆ." },
        { ic: "sprout", t: "ದೀರ್ಘಕಾಲೀನ ಸಂಪತ್ತು ಸೃಷ್ಟಿ", d: "ದಶಕಗಳ ಕಾಲ ಬೆಳೆಯುವ ಶಿಸ್ತು ಮತ್ತು ಅಭ್ಯಾಸಗಳು, ಕ್ಷಣಿಕ ಸುದ್ದಿಗಳಲ್ಲ." },
      ],
    },
    programs: {
      eyebrow: "ಕಲಿಕಾ ಕಾರ್ಯಕ್ರಮಗಳು",
      title: "ಹಂತ ಹಂತವಾಗಿ ರಚನಾತ್ಮಕ ಮಾರ್ಗ",
      sub: "ಹಣದ ಮೂಲಾಂಶಗಳಿಂದ ವಿಶ್ವಾಸಪೂರ್ಣ ಹೂಡಿಕೆಯವರೆಗೆ ಕರೆದೊಯ್ಯುವ ಆರು ಕಾರ್ಯಕ್ರಮಗಳು.",
      tabs: [
        { id: "all", label: "ಎಲ್ಲಾ" },
        { id: "foundations", label: "ಮೂಲಾಂಶಗಳು" },
        { id: "markets", label: "ಮಾರುಕಟ್ಟೆ" },
        { id: "mindset", label: "ಮನೋಭಾವ" },
      ],
      cta: "ಕಾರ್ಯಕ್ರಮ ನೋಡಿ",
      items: [
        { ic: "pie", cat: "markets", t: "ಷೇರು ಮಾರುಕಟ್ಟೆ ಮೂಲಾಂಶಗಳು", d: "ಷೇರುಗಳು, ಸೂಚ್ಯಂಕಗಳು ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ, ಶೂನ್ಯದಿಂದ.", level: "ಆರಂಭಿಕ", modules: "8 ಮಾಡ್ಯೂಲ್" },
        { ic: "layers", cat: "markets", t: "ಮ್ಯೂಚುವಲ್ ಫಂಡ್ ಮತ್ತು SIP", d: "ವೈವಿಧ್ಯಮಯ ಫಂಡ್ ಮತ್ತು ಶಿಸ್ತಿನ SIP ಮೂಲಕ ಸ್ಥಿರವಾಗಿ ಸಂಪತ್ತು ಬೆಳೆಸಿ.", level: "ಆರಂಭಿಕ", modules: "6 ಮಾಡ್ಯೂಲ್" },
        { ic: "wallet", cat: "foundations", t: "ವೈಯಕ್ತಿಕ ಹಣಕಾಸು", d: "ಬಜೆಟ್, ಉಳಿತಾಯ, ಸಾಲ ಮತ್ತು ತುರ್ತು ನಿಧಿ, ನಿಮ್ಮ ಹಣಕಾಸು ಅಡಿಪಾಯ.", level: "ಆರಂಭಿಕ", modules: "7 ಮಾಡ್ಯೂಲ್" },
        { ic: "target", cat: "foundations", t: "ಹಣಕಾಸು ಯೋಜನೆ", d: "ಗುರಿ ಹಾಕಿಕೊಳ್ಳಿ, ಜೀವನದ ಘಟನೆಗಳಿಗೆ ಯೋಜಿಸಿ, ಹಣವನ್ನು ಜೀವನಕ್ಕೆ ಹೊಂದಿಸಿ.", level: "ಮಧ್ಯಮ", modules: "5 ಮಾಡ್ಯೂಲ್" },
        { ic: "brain", cat: "mindset", t: "ಹೂಡಿಕೆದಾರ ಮನೋವಿಜ್ಞಾನ", d: "ನಿಜವಾದ ಲಾಭ ನಿರ್ಧರಿಸುವ ಭಯ, ದುರಾಸೆ, ತಾಳ್ಮೆಯನ್ನು ನಿಯಂತ್ರಿಸಿ.", level: "ಮಧ್ಯಮ", modules: "4 ಮಾಡ್ಯೂಲ್" },
        { ic: "scale", cat: "mindset", t: "ಆಸ್ತಿ ಹಂಚಿಕೆ", d: "ನಿಮ್ಮ ಗುರಿಗೆ ತಕ್ಕಂತೆ ಷೇರು, ಸಾಲ ಮತ್ತು ಚಿನ್ನದಲ್ಲಿ ಅಪಾಯ ಸಮತೋಲನ ಮಾಡಿ.", level: "ಮುಂದುವರಿದ", modules: "5 ಮಾಡ್ಯೂಲ್" },
      ],
    },
    process: {
      eyebrow: "ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
      title: "ನಾಲ್ಕು ಹಂತಗಳಲ್ಲಿ ಗೊಂದಲದಿಂದ ವಿಶ್ವಾಸಕ್ಕೆ",
      sub: "ಶಾಂತ, ಪುನರಾವರ್ತಿಸಬಹುದಾದ ಪ್ರಕ್ರಿಯೆ, ಪ್ರತಿ ಕಲಿಯುವವರೊಂದಿಗೆ ನಾವು ಬಳಸುವ ಅದೇ.",
      steps: [
        { t: "ಕಲಿಯಿರಿ", d: "ಹಣ, ಮಾರುಕಟ್ಟೆ ಮತ್ತು ಹೂಡಿಕೆಯ ಮೂಲಾಂಶಗಳಿಂದ ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಆರಂಭಿಸಿ." },
        { t: "ಅಪಾಯ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ", d: "ಯಾವುದೇ ಲಾಭಕ್ಕಿಂತ ಮೊದಲು, ಏನು ತಪ್ಪಾಗಬಹುದು ಎಂದು ತಿಳಿಯಿರಿ." },
        { t: "ಜ್ಞಾನ ಬೆಳೆಸಿಕೊಳ್ಳಿ", d: "ಸಂಪೂರ್ಣ ಚಿತ್ರ ಸ್ಪಷ್ಟವಾಗುವವರೆಗೆ ಕ್ರಮೇಣ ಪರಿಕಲ್ಪನೆಗಳನ್ನು ಜೋಡಿಸಿ." },
        { t: "ಶಿಸ್ತಿನಿಂದ ಹೂಡಿಕೆ ಮಾಡಿ", d: "ತಿಳಿದದ್ದನ್ನು ತಾಳ್ಮೆಯಿಂದ, ದೀರ್ಘಕಾಲಕ್ಕೆ ಅನ್ವಯಿಸಿ, ನಿಮ್ಮದೇ ರೀತಿಯಲ್ಲಿ." },
      ],
    },
    founder: {
      eyebrow: "ಸಂಸ್ಥಾಪಕರನ್ನು ಭೇಟಿಯಾಗಿ",
      title: "ಇಬ್ಬರು, ಒಂದೇ ಗುರಿ",
      sub: "ಹಣಕಾಸು ಅರಿವಿನ ಕರ್ನಾಟಕವನ್ನು ಕಟ್ಟಲು ನಾವು Wealthoria ಆರಂಭಿಸಿದೆವು, ಸ್ವತಃ ಯೋಚಿಸಬಲ್ಲ ಒಬ್ಬೊಬ್ಬ ಕಲಿಯುವವರ ಮೂಲಕ.",
      people: [
        {
          photoLabel: "ಸಂದೀಪ್ ಫೋಟೋ, ಚಿತ್ರ ಸೇರಿಸಿ",
          name: "ಸಂದೀಪ್ ಎಂ. ಕಲಬುರ್ಗಿ",
          photo: "assets/founder-sandeep.jpg",
          role: "ನಿರ್ದೇಶಕರು, ವ್ಯವಹಾರ ಮತ್ತು ನಿರ್ವಹಣೆ",
          quote: "ನಿಜವಾದ ಸಂಪತ್ತು ಅದೃಷ್ಟದಿಂದಲ್ಲ, ಶಿಸ್ತಿನಿಂದ ಬೆಳೆಯುತ್ತದೆ. ಮೊದಲು ಹಣವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಾವು ಕಲಿಸುತ್ತೇವೆ, ಆಗ ಪ್ರತಿ ನಿರ್ಧಾರವೂ ಅವರದ್ದೇ ಆಗಿರುತ್ತದೆ.",
          creds: [
            "5+ ವರ್ಷಗಳ ವೈಯಕ್ತಿಕ ಹೂಡಿಕೆ ಪಯಣ",
            "ವ್ಯವಹಾರ ತಂತ್ರ ಮತ್ತು ಕಾರ್ಯಾಚರಣೆ",
            "ಕಂಪನಿ ಆಡಳಿತ ಮತ್ತು ನಿರ್ವಹಣೆ",
            "ಪಠ್ಯಕ್ರಮ ವಿನ್ಯಾಸ ಮತ್ತು ಕಾರ್ಯಕ್ರಮ ವಿತರಣೆ",
            "NISM ಪ್ರಮಾಣೀಕರಣಗಳು (NISM I, VA, VII, VIII)",
            "NSE, BSE, MCX ಬ್ರೋಕಿಂಗ್ ಪರವಾನಗಿದಾರ",
          ],
        },
        {
          photoLabel: "ಮಂಜುನಾಥ್ ಫೋಟೋ, ಚಿತ್ರ ಸೇರಿಸಿ",
          name: "ಮಂಜುನಾಥ್ ಕೆ.ಎಸ್.",
          photo: "assets/founder-manjunath.jpg",
          role: "ನಿರ್ದೇಶಕರು, ಸಂಶೋಧನೆ ಮತ್ತು ವಿಷಯ",
          quote: "ಹೂಡಿಕೆಯ ಗುರಿ ಎಲ್ಲರನೂನೂ ಸೋಲಿಸುವುದಲ್ಲ. ನಿಮ್ಮ ಆರ್ಥಿಕ ಸ್ವಾತಂತ್ರ್ಯವನ್ನು ಭದ್ರಪಡಿಸುವುದು.",
          creds: [
            "NISM ಪ್ರಮಾಣೀಕೃತ ಸಂಶೋಧನಾ ವಿಶ್ಲೇಷಕ (ಸರಣಿ XV ಮತ್ತು V)",
            "ವಿಷಯ ಸೃಷ್ಟಿಕರ್ತ, Stock Market Kannada (1L+ ಚಂದಾದಾರರು)",
            "6+ ವರ್ಷಗಳ ಹಣಕಾಸು ವಿಷಯ ಸೃಷ್ಟಿ",
            "ನೇರ ಮಾರುಕಟ್ಟೆ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಹೂಡಿಕೆ ಸಂಶೋಧನೆ",
            "10+ ವರ್ಷಗಳ ವೈಯಕ್ತಿಕ ಹೂಡಿಕೆ ಪಯಣ",
          ],
        },
      ],
    },
    testimonials: {
      eyebrow: "ಕಲಿಯುವವರ ಅಭಿಪ್ರಾಯ",
      title: "ನಿಜವಾದ ಜನರು, ನಿಜವಾದ ತಿಳಿವಳಿಕೆ",
      items: [
        { q: "ಕೇವಲ ಸಲಹೆ ಅನುಸರಿಸುವ ಬದಲು SIP ಮತ್ತು ಅಪಾಯವನ್ನು ಈಗ ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ. ಈಗ ಶಾಂತವಾಗಿ ಸ್ವತಃ ಹೂಡಿಕೆ ಮಾಡುತ್ತೇನೆ.", n: "ಪ್ರಿಯಾ ಆರ್.", r: "ಸಾಫ್ಟ್‌ವೇರ್ ಇಂಜಿನಿಯರ್ · ಬೆಂಗಳೂರು" },
        { q: "ಕನ್ನಡ ತರಗತಿಗಳು ನನ್ನ ಪೋಷಕರಿಗೆ ಎಲ್ಲವನ್ನೂ ಸ್ಪಷ್ಟಪಡಿಸಿದವು. ನಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಹಣಕಾಸು ಅರಿವು ಶಕ್ತಿಶಾಲಿ.", n: "ಮಂಜುನಾಥ್ ಎಸ್.", r: "ಉದ್ಯಮಿ · ಹುಬ್ಬಳ್ಳಿ" },
        { q: "ಯಾವುದೇ ಪ್ರಚಾರವಿಲ್ಲ, ಬೇಗ ಶ್ರೀಮಂತರಾಗುವ ಆಸೆಯಿಲ್ಲ. ಹಣದ ಬಗ್ಗೆ ನನ್ನ ಯೋಚನೆ ಬದಲಿಸಿದ ಸ್ಪಷ್ಟ ಶಿಕ್ಷಣ.", n: "ಅನಿತಾ ಕೆ.", r: "ಕಾಲೇಜು ವಿದ್ಯಾರ್ಥಿನಿ · ಮೈಸೂರು" },
        { q: "ಲಾಭಕ್ಕಿಂತ ಮೊದಲು ಅಪಾಯ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಕಲಿತೆ. ಆ ಒಂದು ಬದಲಾವಣೆ ತಪ್ಪು ನಿರ್ಧಾರದಿಂದ ನನ್ನನ್ನು ಕಾಪಾಡಿತು.", n: "ರಾಹುಲ್ ಡಿ.", r: "ಸಂಬಳದ ವೃತ್ತಿಪರ · ಮಂಗಳೂರು" },
        { q: "ರಚನಾತ್ಮಕ, ತಾಳ್ಮೆ ಮತ್ತು ಪ್ರಾಮಾಣಿಕ. ಹಣಕಾಸು ಶಿಕ್ಷಣ ಹೀಗೆಯೇ ಕಲಿಸಬೇಕು.", n: "ಸಹನಾ ಬಿ.", r: "ಶಿಕ್ಷಕಿ · ಬೆಳಗಾವಿ" },
      ],
    },
    youtube: {
      eyebrow: "ವೀಕ್ಷಿಸಿ ಮತ್ತು ಕಲಿಯಿರಿ",
      title: "ನಮ್ಮ ಚಾನಲ್‌ನಲ್ಲಿ ಉಚಿತ ಪಾಠಗಳು",
      sub: "ಪ್ರತಿ ವಾರ ಪ್ರಕಟವಾಗುವ ಸಣ್ಣ ಹಣಕಾಸು ಪಾಠಗಳು, ಕನ್ನಡ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ.",
      cta: "ನಮ್ಮ ಚಾನಲ್ ನೋಡಿ",
      items: [
        { t: "ಮ್ಯೂಚುವಲ್ ಫಂಡ್ ಎಂದರೇನು? ಸರಳವಾಗಿ ವಿವರಣೆ", dur: "12:40", views: "24K ವೀಕ್ಷಣೆ", tag: "ಮ್ಯೂಚುವಲ್ ಫಂಡ್", feat: true },
        { t: "ಆರಂಭಿಕ ಹೂಡಿಕೆದಾರರು ಮಾಡುವ 5 ಹಣದ ತಪ್ಪುಗಳು", dur: "08:15", views: "18K ವೀಕ್ಷಣೆ", tag: "ವೈಯಕ್ತಿಕ ಹಣಕಾಸು" },
        { t: "SIP vs ಲಂಪ್‌ಸಮ್: ನಿಮಗೆ ಯಾವುದು ಸರಿ?", dur: "10:02", views: "31K ವೀಕ್ಷಣೆ", tag: "ಹೂಡಿಕೆ" },
      ],
    },
    seminars: {
      eyebrow: "ಮುಂಬರುವ ಸೆಮಿನಾರ್‌ಗಳು ಮತ್ತು ಕಾರ್ಯಕ್ರಮಗಳು",
      title: "ನಮ್ಮೊಂದಿಗೆ ಕಲಿಯಿರಿ, ನೇರವಾಗಿ ಮತ್ತು ಆನ್‌ಲೈನ್",
      sub: "ಕರ್ನಾಟಕದಾದ್ಯಂತ ಉಚಿತ ಮತ್ತು ಪಾವತಿ ತರಗತಿಗಳು. ನಿಮ್ಮ ಸ್ಥಾನವನ್ನು ಬೇಗ ಕಾಯ್ದಿರಿಸಿ.",
      cta: "ನೋಂದಣಿ",
      seatsLabel: "ಸ್ಥಾನ ಬಾಕಿ",
      items: [
        { d: "14", m: "ಜೂನ್", t: "ಷೇರು ಮಾರುಕಟ್ಟೆ ಮೂಲಾಂಶಗಳು, ನೇರ ಕಾರ್ಯಾಗಾರ", city: "ಬೆಂಗಳೂರು", mode: "ನೇರವಾಗಿ", seats: "18" },
        { d: "21", m: "ಜೂನ್", t: "ಮ್ಯೂಚುವಲ್ ಫಂಡ್ ಮತ್ತು SIP ಮಾಸ್ಟರ್‌ಕ್ಲಾಸ್ (ಕನ್ನಡ)", city: "ಆನ್‌ಲೈನ್", mode: "ಆನ್‌ಲೈನ್", seats: "120" },
        { d: "05", m: "ಜುಲೈ", t: "ಯುವ ವೃತ್ತಿಪರರಿಗೆ ವೈಯಕ್ತಿಕ ಹಣಕಾಸು", city: "ಹುಬ್ಬಳ್ಳಿ", mode: "ನೇರವಾಗಿ", seats: "32" },
      ],
    },
    library: {
      eyebrow: "ಉಚಿತ ಜ್ಞಾನ ಗ್ರಂಥಾಲಯ",
      title: "ಮಾರ್ಗದರ್ಶಿಗಳು, ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಮತ್ತು ಚೀಟ್‌ಶೀಟ್‌ಗಳು",
      sub: "ತರಗತಿಗಳ ನಡುವೆ ಕಲಿಕೆ ಮುಂದುವರಿಸಲು ಸ್ವಯಂ-ಸೇವಾ ಸಂಪನ್ಮೂಲಗಳು, ಎಲ್ಲವೂ ಉಚಿತ.",
      items: [
        { ic: "file", tag: "ಮಾರ್ಗದರ್ಶಿ", t: "ಹೂಡಿಕೆಗೆ ಆರಂಭಿಕ ಮಾರ್ಗದರ್ಶಿ", d: "ಮೂಲಾಂಶಗಳನ್ನು ಒಳಗೊಂಡ ಸರಳ ಭಾಷೆಯ ಪರಿಚಯ." },
        { ic: "calc", tag: "ಕ್ಯಾಲ್ಕುಲೇಟರ್", t: "SIP ಮತ್ತು ಗುರಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್", d: "ಶಿಸ್ತಿನ ಮಾಸಿಕ ಹೂಡಿಕೆ ಕಾಲಾನಂತರ ಹೇಗೆ ಬೆಳೆಯುತ್ತದೆ ನೋಡಿ." },
        { ic: "list", tag: "ಪರಿಶೀಲನಾ ಪಟ್ಟಿ", t: "ವೈಯಕ್ತಿಕ ಹಣಕಾಸು ಪರಿಶೀಲನಾ ಪಟ್ಟಿ", d: "ಹೂಡಿಕೆಗೆ ಮೊದಲು ಹೊಂದಿಸಬೇಕಾದ 10 ಹಣದ ಅಭ್ಯಾಸಗಳು." },
        { ic: "book", tag: "ಪದಕೋಶ", t: "ಹೂಡಿಕೆ ಪದಗಳ ವಿವರಣೆ", d: "ಪ್ರತಿ ಪ್ರಮುಖ ಪದವೂ ಒಂದೇ ಸರಳ ಸ್ಥಳದಲ್ಲಿ ವಿವರಿಸಲಾಗಿದೆ." },
      ],
    },
    consult: {
      eyebrow: "ಉಚಿತ ಸಮಾಲೋಚನೆ ಕಾಯ್ದಿರಿಸಿ",
      title: "ಎಲ್ಲಿಂದ ಆರಂಭಿಸಬೇಕೋ ತಿಳಿಯುತ್ತಿಲ್ಲವೇ?",
      sub: "ನಿಮ್ಮ ಬಗ್ಗೆ ಸ್ವಲ್ಪ ಹೇಳಿ, ನಾವು ಸರಿಯಾದ ಕಲಿಕಾ ಮಾರ್ಗವನ್ನು ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ, ಸಂಪೂರ್ಣ ಉಚಿತ, ಯಾವುದೇ ಬಾಧ್ಯತೆ ಇಲ್ಲ.",
      points: [
        { ic: "compass", t: "ನಿಮಗೆ ಹೊಂದುವ ಮಾರ್ಗ", d: "ನಿಮ್ಮ ಗುರಿ ಮತ್ತು ಅನುಭವಕ್ಕೆ ಸರಿಯಾದ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಹೊಂದಿಸುತ್ತೇವೆ." },
        { ic: "languages", t: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ", d: "ಕನ್ನಡ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ನಮ್ಮೊಂದಿಗೆ ಮಾತನಾಡಿ." },
        { ic: "shield", t: "ಶಿಕ್ಷಣ, ಮಾರಾಟವಲ್ಲ", d: "ಯಾವುದೇ ಉತ್ಪನ್ನ ತಳ್ಳುವುದಿಲ್ಲ. ಕೇವಲ ಪ್ರಾಮಾಣಿಕ ಮಾರ್ಗದರ್ಶನ." },
      ],
      contacts: [
        { ic: "mail", v: "wealthoria.edu@gmail.com", href: "mailto:wealthoria.edu@gmail.com" },
        { ic: "phone", v: "+91 90197 59001", href: "tel:+919019759001" },
        { ic: "pin", v: "ಮೈಸೂರು, ಕರ್ನಾಟಕ, ಭಾರತ", href: "#" },
      ],
      form: {
        name: "ಪೂರ್ಣ ಹೆಸರು", email: "ಇಮೇಲ್", phone: "ದೂರವಾಣಿ", city: "ನಗರ",
        interest: "ನನಗೆ ಆಸಕ್ತಿ ಇದೆ", message: "ನಮಗೆ ತಿಳಿಸಲು ಬಯಸುವುದೇ? (ಐಚ್ಛಿಕ)",
        interestOpts: ["ಷೇರು ಮಾರುಕಟ್ಟೆ ಮೂಲಾಂಶಗಳು", "ಮ್ಯೂಚುವಲ್ ಫಂಡ್ ಮತ್ತು SIP", "ವೈಯಕ್ತಿಕ ಹಣಕಾಸು", "ಹಣಕಾಸು ಯೋಜನೆ", "ಇನ್ನೂ ಖಚಿತವಿಲ್ಲ, ಮಾರ್ಗದರ್ಶನ ಮಾಡಿ"],
        submit: "ಉಚಿತ ಸಮಾಲೋಚನೆ ವಿನಂತಿಸಿ",
        placeholderName: "ಉದಾ. ಆನಂದ್ ಕುಮಾರ್", placeholderEmail: "you@email.com",
        placeholderPhone: "+91 ", placeholderCity: "ಉದಾ. ಬೆಂಗಳೂರು",
        placeholderMsg: "ನಿಮ್ಮ ಗುರಿ, ಪ್ರಶ್ನೆಗಳು ಅಥವಾ ಆದ್ಯತೆಯ ಭಾಷೆ…",
        errName: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ", errEmail: "ಮಾನ್ಯ ಇಮೇಲ್ ನಮೂದಿಸಿ", errPhone: "ಮಾನ್ಯ ದೂರವಾಣಿ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
        successTitle: "ವಿನಂತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ", successMsg: "ಧನ್ಯವಾದಗಳು! ನಿಮ್ಮ ಉಚಿತ ಸಮಾಲೋಚನೆಗೆ ಒಂದು ಕೆಲಸದ ದಿನದೊಳಗೆ ನಮ್ಮ ತಂಡ ಸಂಪರ್ಕಿಸುತ್ತದೆ.",
      },
    },
    faq: {
      eyebrow: "ಪದೇ ಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು",
      title: "ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರ",
      items: [
        { q: "ಆರಂಭಿಸಲು ಪೂರ್ವ ಜ್ಞಾನ ಬೇಕೆ?", a: "ಇಲ್ಲ. ನಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳು ಹಣದ ಮೂಲಾಂಶಗಳಿಂದ ಆರಂಭವಾಗಿ ಕ್ರಮೇಣ ಬೆಳೆಯುತ್ತವೆ, ಆದ್ದರಿಂದ ಮೊದಲ ಬಾರಿಯ ಕಲಿಯುವವರೂ ಸುಲಭವಾಗಿ ಕಲಿಯಬಹುದು." },
        { q: "ತರಗತಿಗಳು ಕನ್ನಡದಲ್ಲಿ ಲಭ್ಯವೇ?", a: "ಹೌದು. ಪ್ರಮುಖ ಕಾರ್ಯಕ್ರಮಗಳು ಮತ್ತು ಹಲವು ಸೆಮಿನಾರ್‌ಗಳು ಕನ್ನಡ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಲಭ್ಯವಿದೆ." },
        { q: "Wealthoria ಷೇರು ಸಲಹೆ ನೀಡುತ್ತದೆಯೇ?", a: "ಇಲ್ಲ. ನಾವು ಹಣಕಾಸು ಶಿಕ್ಷಣ ಸಂಸ್ಥೆ. ಸ್ವತಃ ಯೋಚಿಸಿ ನಿರ್ಧರಿಸುವುದನ್ನು ಕಲಿಸುತ್ತೇವೆ, ಯಾವುದೇ ಸಲಹೆ ನೀಡುವುದಿಲ್ಲ." },
        { q: "ಕಾರ್ಯಕ್ರಮಗಳು ಯಾರಿಗಾಗಿ?", a: "ಮೊದಲ ಬಾರಿಯ ಹೂಡಿಕೆದಾರರು, ಯುವ ವೃತ್ತಿಪರರು, ಸಂಬಳದವರು, ಉದ್ಯಮಿಗಳು ಮತ್ತು ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ." },
        { q: "ಆರಂಭಿಸಲು ಉಚಿತ ಸಂಪನ್ಮೂಲಗಳಿವೆಯೇ?", a: "ಹೌದು. ನಮ್ಮ ಯೂಟ್ಯೂಬ್ ಚಾನಲ್, ಜ್ಞಾನ ಗ್ರಂಥಾಲಯ ಮತ್ತು ಆಯ್ದ ಸೆಮಿನಾರ್‌ಗಳು ಸಂಪೂರ್ಣ ಉಚಿತ." },
        { q: "ಸಮಾಲೋಚನೆ ಹೇಗೆ ಕಾಯ್ದಿರಿಸುವುದು?", a: "ಮೇಲಿನ ಫಾರ್ಮ್ ಬಳಸಿ. ನಿಮ್ಮ ಗುರಿ ಹೇಳಿ, ನಾವು ಸರಿಯಾದ ಮಾರ್ಗ ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ, ಉಚಿತ." },
      ],
    },
    footer: {
      blurb: "Wealthoria ಒಂದು ಹಣಕಾಸು ಶಿಕ್ಷಣ ಸಂಸ್ಥೆ, ಹಣಕಾಸು ಅರಿವಿನ ಭಾರತವನ್ನು ಕಟ್ಟುವ ಗುರಿ. ಹೂಡಿಕೆಗೆ ಮೊದಲು ಕಲಿಕೆ, ವ್ಯಾಪಾರಕ್ಕಿಂತ ಮೊದಲು ಹೂಡಿಕೆ.",
      newsletter: "ಪ್ರತಿ ವಾರ ನಿಮ್ಮ ಇನ್‌ಬಾಕ್ಸ್‌ಗೆ ಉಚಿತ ಪಾಠ",
      newsletterCta: "ಸೇರಿ",
      cols: [
        { h: "ಕಲಿಕೆ", links: ["ಕಾರ್ಯಕ್ರಮಗಳು", "ಸೆಮಿನಾರ್‌ಗಳು", "ಜ್ಞಾನ ಗ್ರಂಥಾಲಯ", "ಯೂಟ್ಯೂಬ್ ಚಾನಲ್"] },
        { h: "ಸಂಸ್ಥೆ", links: ["ನಮ್ಮ ಬಗ್ಗೆ", "ಸಂಸ್ಥಾಪಕರ ದೃಷ್ಟಿ", "ವೃತ್ತಿ", "ಸಂಪರ್ಕ"] },
        { h: "ಸಂಪನ್ಮೂಲ", links: ["ಆರಂಭಿಕ ಮಾರ್ಗದರ್ಶಿ", "ಕ್ಯಾಲ್ಕುಲೇಟರ್", "ಪದಕೋಶ", "ಬ್ಲಾಗ್"] },
        { h: "ಕಾನೂನು", links: ["ಗೌಪ್ಯತಾ ನೀತಿ", "ಬಳಕೆ ನಿಯಮಗಳು", "ಹಕ್ಕು ನಿರಾಕರಣೆ", "ಮರುಪಾವತಿ ನೀತಿ"] },
      ],
      disclaimer: "Wealthoria ಕೇವಲ ಹಣಕಾಸು ಶಿಕ್ಷಣವನ್ನು ಒದಗಿಸುತ್ತದೆ ಮತ್ತು ಹೂಡಿಕೆ ಸಲಹೆ ಅಥವಾ ಖಾತರಿ ಲಾಭವನ್ನು ನೀಡುವುದಿಲ್ಲ. ಹೂಡಿಕೆಗಳು ಮಾರುಕಟ್ಟೆ ಅಪಾಯಗಳಿಗೆ ಒಳಪಟ್ಟಿವೆ.",
      copyright: "© 2026 Wealthoria Education Private Limited",
    },
  },
};

window.CONTENT = CONTENT;
